- name: Install packages on Ubuntu
  environment:
    http_proxy: http://135.245.48.34:8000
    https_proxy: http://135.245.48.34:8000
    no_proxy: 192.168.39.0/24,192.168.122.0/24,172.22.0.0/24,192.168.111.0/24,svc,helion-bld08,0.0.0.0,localhost
  block:
    - name: Install required packages for Ubuntu
      include_tasks: ubuntu_required_packages.yml
    - name: Install common packages using standard package manager for Ubuntu
      package:
        name: "{{ packages.ubuntu.common.packages}}"
        state: present
    - name: Install packages using standard package manager for Ubuntu 18.04
      when: ansible_distribution_version == "18.04"
      package:
        name: "{{ packages.ubuntu.bionic.packages}}"
        state: present
    - name: Install packages using standard package manager for Ubuntu 20.04 or Ubuntu 22.04
      when: ansible_distribution_version == "20.04" or ansible_distribution_version == "22.04"
      package:
        name: "{{ packages.ubuntu.focal_jammy.packages}}"
        state: present
      become: yes
    - name: Install packages specific to Podman
      package:
        name: "{{ packages.ubuntu.podman.packages}}"
        state: present
      when: CONTAINER_RUNTIME == "podman"
      become: yes
    - name: Install packages using pip3
      pip:
        executable: "pip3"
        name: "{{ packages.ubuntu.pip3 }}"
        state: present
    - name: Add TPM emulator
      block:
        - name: Add TPM emulator PPA
          apt_repository:
            repo: 'ppa:smoser/swtpm'
            state: present
          become: yes
        - name: Install TPM emulator packages
          package:
            name:
              - swtpm
              - libtpms
            state: present
          become: yes
      when: tpm_emulator|default(false)|bool
  become: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install packages on CentOS/RHEL8
  environment:
    http_proxy: http://135.245.48.34:8000
    https_proxy: http://135.245.48.34:8000
    no_proxy: 192.168.39.0/24,192.168.122.0/24,172.22.0.0/24,192.168.111.0/24,svc,helion-bld08,0.0.0.0,localhost
  block:
    - name: Install packages on CentOS/RHEL
      package:
          name: "{{ packages.centos.common.packages }}"
          state: present
    - name: Install packages on CentOS8/RHEL8
      package:
          name: "{{ packages.centos.el8.packages }}"
          state: present
      when: ansible_distribution_version == "8"
    - name: Install packages on CentOS9/RHEL9
      package:
          name: "{{ packages.centos.el9.packages }}"
          state: present
      when: ansible_distribution_version == "9"
    - name: Perform CentOS/RHEL8 required configurations
      include_tasks: centos_required_packages.yml
    - name: Install packages using pip3
      pip:
        executable: "pip3"
        name: "{{ packages.centos.pip3 }}"
        extra_args: "--proxy http://135.245.48.34:8000 --ignore-installed PyYAML"
        state: present
    - name: Install TPM emulator packages
      when: tpm_emulator|default(false)|bool
      package:
        name:
          - swtpm
          - swtpm-tools
        state: present
      become: yes
  become: yes
  when: ansible_os_family == "RedHat"
