---
- name: Setup dummy baremetal VMs
  hosts: virthost
  connection: local
  gather_facts: true
  tasks:
    - import_role:
        name: firewall
  environment:
    http_proxy: http://proxy.lbs.alcatel-lucent.com:8000
    https_proxy: http://proxy.lbs.alcatel-lucent.com:8000
