---
- name: Install packages needed for the Dev-env
  hosts: virthost
  connection: local
  gather_facts: true
  tasks:
    - import_role:
        name: packages_installation
    - import_role:
        name: fubarhouse.golang
      vars:
        go_version: 1.17.5
        go_install_clean: true
  environment:
    http_proxy: http://proxy.lbs.alcatel-lucent.com:8000
    https_proxy: http://proxy.lbs.alcatel-lucent.com:8000
