---
- name: Install packages needed for the Dev-env
  hosts: virthost
  connection: local
  gather_facts: true
  tasks:
    - import_role:
        name: packages_installation
    - import_role:
        name: fubarhouse.golang
      vars:
        go_version: 1.17.5
        go_install_clean: true
  environment:
    http_proxy: http://135.245.48.34:8000
    https_proxy: http://135.245.48.34:8000
    no_proxy: 192.168.39.0/24,192.168.122.0/24,172.22.0.0/24,192.168.111.0/24,svc,helion-bld08,0.0.0.0,localhost
