---
- name: Setup dummy baremetal VMs
  hosts: virthost
  connection: local
  gather_facts: true
  tasks:
    - import_role:
        name: common
    - import_role:
        name: libvirt
    - import_role:
        name: virtbmc
      when: vm_platform|default("libvirt") == "libvirt"
  environment:
    http_proxy: http://135.245.48.34:8000
    https_proxy: http://135.245.48.34:8000
    no_proxy: 192.168.39.0/24,192.168.122.0/24,172.22.0.0/24,192.168.111.0/24,svc,helion-bld08,0.0.0.0,localhost
