---
- name: Teardown previous libvirt setup
  hosts: virthost
  connection: local
  gather_facts: true
  tasks:
    - import_role:
        name: common
    - import_role:
        name: libvirt
      vars:
        libvirt_action: "teardown"
    - import_role:
        name: virtbmc
      vars:
        virtbmc_action: "teardown"
  environment:
    http_proxy: http://proxy.lbs.alcatel-lucent.com:8000
    https_proxy: http://proxy.lbs.alcatel-lucent.com:8000
